name: check_folder_changes_manual
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  ENV: staging
  IN_AUTOMATION: 1
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
jobs:
  check_branch:
    runs-on: ubuntu-latest
    name: check_if_branch_is_main
    steps:
      - name: test
        uses: actions/checkout@v3
      - id: filter
        run: |
          echo "${{ github.ref }}"
          echo ${{ github.ref }}
          if [[ "${{ github.ref }}" != "refs/heads/master" ]]; then
            echo "Branch is not master, exiting."
            exit 0
          fi
        

  pkrbuild_test:
   name: pkrbuild_test
   runs-on: ubuntu-latest
   steps:
     - name: Clone repo
       uses: actions/checkout@v3
       with:
         ref: main

  subsequent_pkrbuild_test:
   name: subsequent_pkrbuild_test
   runs-on: ubuntu-latest
   steps:
     - name: Clone repo
       uses: actions/checkout@v3
       with:
         ref: main
