name: check_folder_changes
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  ENV: staging
  IN_AUTOMATION: 1
  PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
jobs:
  check_folder_changes:
    runs-on: ubuntu-latest
    name: check_if_packer_code_chaged
    outputs:
      folder_changed: ${{ steps.filter.outputs.folder_changed }}
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
          ref: main
      - id: filter
        run: |
          echo "Checking for changes in 'packer/'..."
          git fetch --depth=1 origin main
          git diff origin main -- ./packer
          if ! git diff --quiet origin/main -- ./packer; then
            echo "folder_changed=true" >> $GITHUB_OUTPUT
          else
            echo "folder_changed=false" >> $GITHUB_OUTPUT
          fi

  pkrbuild_test:
   needs: check_folder_changes
   if: needs.check_folder_changes.outputs.folder_changed == 'true'
   name: pkrbuild_test
   runs-on: ubuntu-latest
   steps:
     - name: Clone repo
       uses: actions/checkout@v3
       with:
         ref: main
